### ISSUE TITLE
Разработчик презирает язык программирования C++. Это является дискриминацией, необходимо подать на него заявление в суд 

### ISSUE THREAD

**Issue by TheLifeWorm** [st0pcha/discord-bot-kt#2]
Я лично считаю, что его отказ является грубым нарушением прав. И является грубым нарушением закона, я как юрист с 10-ти летним стажем заявляю, что он нарушает статью ук рф 282.
![image](https://user-images.githubusercontent.com/48316246/181295308-c6700aa6-1095-49d6-a163-8507ecb8756c.png)

**Comment by st0pcha** [comment]
Отказано. Вы смотрите Хауди Хо Python-курсы.

**Comment by TheLifeWorm** [comment]
Нет. Не правда, я напишу заявление в суд. Ждите суда в течении 3-х месяцев
